{
 "title": "API Server",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "API Errors",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "api_service_emojify_called_count{status!=\"200\"}+api_service_cache_called_count{status!=\"200\"}"
    }
   ]
  },
  {
   "title": "API Request Count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "api_service_emojify_called_count{status=\"200\"}+api_service_cache_called_count{status=\"200\"}",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Emojify API Request Duration /",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "rate(api_service_emojify_called_sum[30s])/rate(api_service_emojify_called_count[30s])"
    },
    {}
   ]
  },
  {
   "title": "Emojify API Request Duration /cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "rate(api_service_cache_called_sum[30s])/rate(api_service_cache_called_count[30s])"
    }
   ]
  },
  {
   "title": "Emojify Face Detect Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "rate(api_service_emojify_find_faces_sum[30s])/rate(api_service_emojify_find_faces_count[30s])"
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(api_service_health_called_count[1m])"
    }
   ]
  }
 ]
}