{
 "title": "Emojify Ingress",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Envoy Requests Inbound",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_local_app_upstream_rq_total{app=\"emojify-ingress\"}[30s])"
    }
   ]
  },
  {
   "title": "API Upstream Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_service_emojify_api_upstream_rq_total[30s])"
    }
   ]
  },
  {
   "title": "Website Upstream Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_service_emojify_website_upstream_rq_total[30s])"
    }
   ]
  },
  {
   "title": "API Requests (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_service_emojify_api_upstream_cx_connect_ms[30s])"
    }
   ]
  },
  {
   "title": "Website Requests (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_service_emojify_website_upstream_cx_connect_ms[30s])"
    }
   ]
  }
 ]
}