---
version: '3'
services:

  consul:
    image: consul:latest
    ports:
      - "8501:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - SERVICE_IGNORE=true

  consul-registrator:
    image: gliderlabs/registrator:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: ["consul://consul:8500"]
    depends_on:
      - consul

  nginx:
    image: nginx:latest
    volumes:
      - ./docker-compose-nginx-default.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8181:80"
    depends_on:
      - consul

  nginx-proxy:
    image: consul:latest
    network_mode: "service:nginx"
    entrypoint: "consul"
    command: [
      'connect',
      'proxy',
      '-log-level=DEBUG',
      '-service', 'nginx',
      '-http-addr', 'consul:8500',
      '-upstream', 'emojify-website:8000',
      '-upstream', 'emojify-api:8002'
    ]
    environment:
      - SERVICE_IGNORE=true
    depends_on:
      - consul

  emojify-website-1:
    image: nicholasjackson/emojify-website:0.5.8
    ports:
      - "5000:5000"
    environment:
      - SERVICE_NAME=emojify-website
      - SERVICE_5000_CHECK_HTTP=/
      - SERVICE_5000_CHECK_INTERVAL=15s
      - SERVICE_5000_CHECK_TIMEOUTL=1s
    volumes:
      - ./docker-compose.env.js:/app/build/config/env.js

  emojify-website-proxy-1:
    image: consul:latest
    entrypoint: "consul"
    network_mode: "service:emojify-website-1"
    command: [
      'connect',
      'proxy',
      '-log-level=DEBUG',
      '-service', 'emojify-website',
      '-http-addr', 'consul:8500',
      '-listen', 'emojify-website-1:8443',
      '-service-addr', 'localhost:5000',
      '-register'
    ]
    environment:
      - SERVICE_IGNORE=true
    depends_on:
      - consul
  
  emojify-website-2:
    image: nicholasjackson/emojify-website:0.5.8
    ports:
      - "5001:5000"
    environment:
      - SERVICE_NAME=emojify-website
      - SERVICE_5000_CHECK_HTTP=/
      - SERVICE_5000_CHECK_INTERVAL=15s
      - SERVICE_5000_CHECK_TIMEOUTL=1s
    volumes:
      - ./docker-compose.env.js:/app/build/config/env.js

  emojify-website-proxy-1:
    image: consul:latest
    entrypoint: "consul"
    network_mode: "service:emojify-website-2"
    command: [
      'connect',
      'proxy',
      '-log-level=DEBUG',
      '-service', 'emojify-website',
      '-http-addr', 'consul:8500',
      '-listen', 'emojify-website-2:8443',
      '-service-addr', 'localhost:5000',
      '-register'
    ]
    environment:
      - SERVICE_IGNORE=true
    depends_on:
      - consul

  emojify-auth:
    image: keratin/authn-server:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=sqlite3://:memory:?mode=memory\&cache=shared
      - AUTHN_URL=http://localhost:3000
      - APP_DOMAINS=localhost
      - PROXIED=true
      - SECRET_KEY_BASE=changeme
      - SERVICE_NAME=emojify-auth
      - SERVICE_3000_CHECK_HTTP=/health
      - SERVICE_3000_CHECK_INTERVAL=15s
      - SERVICE_3000_CHECK_TIMEOUTL=1s
    entrypoint: "sh"
    command: ["-c", "./authn migrate && ./authn server"]

  emojify-auth-proxy:
    image: consul:latest
    entrypoint: "consul"
    network_mode: "service:emojify-auth"
    command: [
      'connect',
      'proxy',
      '-log-level=DEBUG',
      '-service', 'emojify-auth',
      '-http-addr', 'consul:8500',
      '-listen', 'emojify-auth:8443',
      '-service-addr', 'localhost:3000',
      '-register'
    ]
    environment:
      - SERVICE_IGNORE=true
    depends_on:
      - consul

  emojify-api:
    image: "nicholasjackson/emojify-api:0.5.6"
    ports:
      - "9090:9090"
    entrypoint: "/service/emojify-api"
    command: [
      "-allow-origin=*",
      "-authn-server=http://localhost:3000",
      "-authn-audience=localhost",
      "-bind-address=0.0.0.0:9090",
      "-authn-disable=true",
      "-payment-address=http://localhost:8004"
    ]
    environment:
      - FACEBOX=http://localhost:8003
      - SERVICE_NAME=emojify-api
      - SERVICE_9090_CHECK_HTTP=/health
      - SERVICE_9090_CHECK_INTERVAL=15s
      - SERVICE_9090_CHECK_TIMEOUTL=1s

  emojify-api-proxy:
    image: consul:latest
    entrypoint: "consul"
    network_mode: "service:emojify-api"
    command: [
      'connect',
      'proxy',
      '-log-level=DEBUG',
      '-service', 'emojify-api',
      '-http-addr', 'consul:8500',
      '-listen', 'emojify-api:8443',
      '-service-addr', 'emojify-api:9090',
      '-register',
      '-upstream', 'emojify-facebox:8003',
      '-upstream', 'emojify-auth:3000',
      '-upstream', 'emojify-payments:8004',
    ]
    environment:
      - SERVICE_IGNORE=true
    depends_on:
      - consul

  emojify-payments:
    image: "nicholasjackson/emojify-payments:0.5.4"
    ports:
      - "9000:8080"
    environment:
      - MB_KEY=${MB_KEY}
      - SERVICE_NAME=emojify-payments
      - SERVICE_9000_CHECK_HTTP=/health
      - SERVICE_9000_CHECK_INTERVAL=15s
      - SERVICE_9000_CHECK_TIMEOUTL=1s

  emojify-payments-proxy:
    image: consul:latest
    entrypoint: "consul"
    network_mode: "service:emojify-payments"
    command: [
      'connect',
      'proxy',
      '-log-level=DEBUG',
      '-service', 'emojify-payments',
      '-http-addr', 'consul:8500',
      '-listen', 'emojify-payments:8443',
      '-service-addr', 'emojify-payments:8080',
      '-register',
    ]
    environment:
      - SERVICE_IGNORE=true
    depends_on:
      - consul

  emojify-facebox:
    image: "machinebox/facebox:latest"
    ports:
      - "8080:8080"
    environment:
      - MB_KEY=${MB_KEY}
      - SERVICE_NAME=emojify-facebox
      - SERVICE_8080_CHECK_HTTP=/healthz
      - SERVICE_8080_CHECK_INTERVAL=15s
      - SERVICE_8080_CHECK_TIMEOUTL=1s

  emojify-facebox-proxy:
    image: consul:latest
    entrypoint: "consul"
    network_mode: "service:emojify-facebox"
    command: [
      'connect',
      'proxy',
      '-log-level=DEBUG',
      '-service', 'emojify-facebox',
      '-http-addr', 'consul:8500',
      '-listen', 'emojify-facebox:8443',
      '-service-addr', 'localhost:8080',
      '-register',
    ]
    environment:
      - SERVICE_IGNORE=true
    depends_on:
      - consul
