---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: consul-api-v2-mapping
  namespace: default
spec:
  prefix: /api/
  timeout_ms: 20000
  host: emojify.today
  service: emojify-api-v2-sidecar-proxy
  resolver: consul-dc1
  tls: ambassador-consul
  load_balancer:
    policy: round_robin
  retry_policy:
    retry_on: "5xx"
    num_retries: 10
    per_try_timeout: "5s"
