apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: honeycomb-opentracing-proxy
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: honeycomb-opentracing-proxy
    spec:
      containers:
      - name: honeycomb-opentracing-proxy
        image: honeycombio/honeycomb-opentracing-proxy
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9411
        args:
          - -d
          - emojify
          - --debug
          - -k
          - "$(HONEYCOMB_WRITEKEY)"
        env:
        - name: HONEYCOMB_WRITEKEY
          valueFrom:
            secretKeyRef:
              key: key
              name: honeycomb-writekey

---
apiVersion: v1
kind: Service
metadata:
  name: honeycomb-opentracing-proxy
  labels:
    app: honeycomb-opentracing-proxy
spec:
  selector:
    app: honeycomb-opentracing-proxy
  ports:
  - name: http
    port: 9411
    targetPort: http
  type: NodePort
