---
apiVersion: v1
kind: Service
metadata:
  name: consul-public
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8500
  selector:
    app: consul
    component: server
    release: consul
